apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deploy
spec:
  template:
    metadata:
      name: nginx-test-pod
      labels:
        app: nginx-test-pod
    spec:
      containers:
        - name: nginx-test-container
          image: nginx:stable
          ports:
            - containerPort: 80 
        # envFrom:
        #   - configMapRef:
        #       name: portal-configmap
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test-pod

