apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    app: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports: 
        - containerPort: 80
      volumeMounts:
        - mountPath: /first-volume-container
          name: first-volume
    - name: jenkins-container
      image: jenkins:latest
      ports: 
        - containerPort: 80
      volumeMounts:
        - mountPath: /first-volume-container
          name: first-volume
  volumes:
    - name: first-volume
      hostPath:
        path: /home/first-volume
        type: DirectoryOrCreate
