apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports: 
        - containerPort: 80
      volumeMounts:
        - mountPath: /first-volume-container
          name: first-pv
  volumes:
    - name: first-pv
      persistentVolumeClaim:
        claimName: pvc-1

